### ISSUE TITLE
I have some qs 

### ISSUE THREAD

**Issue by ysdokok** [nnhubbard/ZSSRichTextEditor#101] opened 2015-11-10 08:55 UTC
First, I enter the text and pictures ,then I entered in the middle of the text,Then again at the bottom of the screen to enter text will appear jitter. Could you look at it ?

**Comment by william205** [comment] 2016-09-02 22:23
@ysdokok I have been unable to reproduce your issue on any simulator devices or iOS versions so I am going to close this issue.

**Closed by william205** 2016-09-02 22:23 UTC
