### ISSUE TITLE
why in my app, toolbar have a black view?

### ISSUE THREAD

**Issue by lin493369** [nnhubbard/ZSSRichTextEditor#125] opened 2016-06-07 15:07 UTC
![simulator screen shot 2016 6 7 11 06 44](https://cloud.githubusercontent.com/assets/8255169/15863195/942f415a-2d04-11e6-9bc4-f5f8b8234bac.png)

**Comment by nnhubbard** [comment] 2016-06-07 15:53
Have you tried making your view backgroundColor white?

**Comment by william205** [comment] 2016-09-02 22:45
@lin493369 I have been unable to reproduce this issue so I am going to close it for now, if you can provide clear steps to reproduce this issue and I am able to reproduce it then I will re-open it.

**Closed by william205** 2016-09-02 22:45 UTC

**Comment by Cr0sSS** [comment] 2017-05-08 17:38
Same thing. iOS 10.3, iPhone 7 simulator and iPhone 7Plus device.

There is "extraHeight" constant in file ZSSRichTextEditor.m
line 1230

// Editor View
const int extraHeight = 10;

If it = 0, no black line will be shown. For what this magical constant was created?
