### ISSUE TITLE
Blockquote and Enter Key

### ISSUE THREAD

**Issue by richardortiz84** [nnhubbard/ZSSRichTextEditor#32] opened 2014-09-03 04:09 UTC
If I press enter while inside of a blockquote tag, it adds a new blockquote tag immediately after the original tag instead of just adding a br tag inside the existing tag.

**Comment by haigowtham** [comment] 2016-01-25 09:47
How to implement block quote ??can you guide me

**Comment by william205** [comment] 2016-09-02 22:55
![screen shot 2016-09-02 at 23 30 45](https://cloud.githubusercontent.com/assets/9343487/18220299/7a4eb4de-7168-11e6-845a-5ccb36b6fbe6.png)

@haigowtham the circled button will add a block quote.

@richardortiz84 I have been unable to reproduce this so I am going to close this issue for now.

**Closed by william205** 2016-09-02 22:55 UTC
