### ISSUE TITLE
Toolbar button status (black or blue colour) does not change on selected text

### ISSUE THREAD

**Issue by kostastsi** [nnhubbard/ZSSRichTextEditor#112] opened 2016-02-10 14:12 UTC
Write any text you want. Then, select a part of it and press any style button, for example bold one.The selected text turns into bold style but the button remains blue. If you deselect the text and then select it again, works fine, by showing the bold button black. Same behaviour is replicated while selecting a bolded text and try to unbold its style. Please provide any advice or fix.

**Comment by angBiu** [comment] 2016-02-15 06:17
I have the same problem.If you have solve it,please share it.Thank you.

**Comment by kostastsi** [comment] 2016-02-15 10:10
No, i haven't solved it. I am waiting for a possible fix too.

**Comment by nnhubbard** [comment] 2016-02-15 16:45
Happy to take pull requests for this. I just don't have time right now to address the issue.

**Comment by kcrawded** [comment] 2016-03-02 14:18
iOS 8.3 works just fine. But on iOS 9.0 and higher same problem as described above.

**Comment by angBiu** [comment] 2016-03-21 05:38
The zss_editor.setUnderline and zss_editor.setStrikeThrough cannot contain in one word!

**Comment by nnhubbard** [comment] 2016-03-21 20:40
@angBiu Not sure what you mean.

**Comment by angBiu** [comment] 2016-03-29 02:43
@nnhubbard  Sorry,I can't express it clearly.When you set the word with the style 'underline' and 'strikeThrough',input some words,then you set the style 'underline' or 'strikeThrough',the words style will disappear.Sorry for my poor English.Thanks.

**Comment by william205** [comment] 2016-09-02 22:39
@kostastsi I have been unable to reproduce this so I am going to close this issue.

@angBiu your issue to do with underline and strikethrough is in another open issue which I am looking into.

**Closed by william205** 2016-09-02 22:39 UTC
